print('1')
print('12')
print('123')
print('1234')
print('12345')
print('12345')
print('1234')
print('123')
print('12')
print('1')
print('             * * * * * * * *')
print('           * *           * *')
print('          *  *          *  *')
print('         *   *         *   *')
print('         * * * * * * * *   *')
print('         *   *         *   *')
print('         *   *         *   *')
print('         *   *         *   *')
print('         *   *         *   *')
print('         *   * * * * * * * *')
print('         *  *          *  *')
print('         * *           * *')
print('         * * * * * * * * ')
print( "assalomu alaykum men o'zbekiston fuqurosaman")
print('12345')
print('1234')
print('123')
print('12')
print('1')
print('1')
print('12')
print('123')
print('1234')
print('12345')
print('54321')
print('5432')
print('543')
print('54')
print('5')
print('1')
print('22')
print('333')
print('4444')
print('55555')
print('1')
print('12')
print('123')
print('1234')
print('12345')
print('12345')
print('1234')
print('123')
print('12')
print('1')
print('     1')
print('    121')
print('   12321')
print('  1234321')
print(' 123454321')
print('1')
print('12')
print('123')
print('1234')
print('12345')
print('1234')
print('123')
print('12')
print('1')
print('     0')
print('    101')
print('   21012')
print('  3210123')
print(' 432101234')
print('54321012345')
print('*')
print('* *')
print('* * *')
print('* * * *')
print('* * * * *')
print('     *')
print('    * *')
print('   * * *')
print('  * * * *')
print(' * * * * *')
print('* * * * *')
print('* * * *')
print('* * *')
print('* *')
print('*')
print('* * * * *')
print(' * * * *')
print('  * * *')
print('   * *')
print('    *')
print('     *')
print('   * * *')
print('  * * * *')
print(' * * * * *')
print('* * * * * *')
print(' * * * * *')
print('  * * * *')
print('   * * *')
print('    * *')
print('     *')
print('     *')
print('   * * *')
print('  * * * *')
print(' * * * * *')
print('* * * * * *')
print('1 1 1 1 1')
print('1 0 0 0 1')
print('1 0 0 0 1')
print('1 0 0 0 1')
print('1 1 1 1 1')
print('   *******')
print(' *   *     *')
print(' *         ****')
print('   ****     *')
print('   *        ****')
print('   *        *            * *         ***')
print('   *        *           *   *       *   *       ***          * *')
print('   *        *           *   *       *   *      *   *       *   *')
print('   *        *           *   *       *   *      *   *     *   *')
print('   *        ************     *******     ***********   *    *')
print('   *                    * * *       * * *            *     *')
print('   *                                                     *')
print('   *                                                   *')
print('   *                                                 *')
print('      *              * * * * * * * * *             *')
print('      *            *                  *         *')
print('      *            *                  *        *')
print('      *            *                  *        *')
print('   *               *               *           *')
print('     * * * * * * * *                 * * * * * *')


    